name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    # This step forces Git to use the built-in GitHub Token for all downloads!
    - name: Configure Git for Swift Package Manager
      run: git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
        
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
